name: brick_breaker
description: "Re-implementing Woz's Breakout"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flame: ^1.11.0
  flame_audio: ^2.1.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/audio/game_over.mp3
    - assets/audio/brick_break.mp3
    - assets/audio/win.mp3

  uses-material-design: true
